CSCEXAM-1212 Modify question search to work using only user parameter
CSCfi/exam pull request #1033
Opened 2024-01-29 11:31 UTC by VirmasaloA

2024-01-30 17:35 UTC, lupari requested changes

2024-01-30 17:35 UTC, lupari commented on conf/routes
> ++nocsrf
Sen pitäisi kyllä toimia automaattisesti. Jos sulla on ollut joku lokaali ongelma CSRF-tokenien kanssa, niin kantsii tyhjentää selaimesta cookiet tai kokeilla incognito-moodissa uusiksi.

2024-01-30 17:35 UTC, lupari commented on ui/src/app/question/library/search/library-search.component.ts
> +                isSectionTag: false,
Tuo isSectionTag on obsolete, ei käyttöä enää sen jälkeen kun aihealueet meni omaan valikkoon.

2024-01-30 17:35 UTC, lupari commented on ui/src/app/question/library/search/library-search.component.ts
> +          isSectionTag: false,
Sama kuin yllä

2024-02-05 08:34 UTC, VirmasaloA commented on conf/routes
> ++nocsrf
Joo, Tän ei pitäny olla mukana, hyvä kun bongasit.

2024-02-08 10:38 UTC, lupari commented on ui/.bsp/sbt.json
> +{"name":"sbt","version":"1.5.5","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java","-Xms100m","-Xmx100m","-classpath","/us
pois

2024-02-08 10:38 UTC, lupari commented on ui/project/build.properties
> +sbt.version=1.5.5
pois

2024-02-08 10:40 UTC, lupari commented on ui/src/app/question/library/results/library-results.component.html
> +                            by=""
eikö tässä pidä olla creator?

2024-02-12 13:19 UTC, VirmasaloA commented on ui/src/app/question/library/results/library-results.component.html
> +                            by=""
Joo

2024-02-12 17:19 UTC, lupari approved these changes

2024-02-14 08:18 UTC, merged