CSCEXAM-1163 Fix examination question hide button accessibility
CSCfi/exam pull request #1151
Opened 2024-09-03 07:28 UTC by VirmasaloA

2024-09-03 07:31 UTC, VirmasaloA commented
Poistin samalla parista muustakin kohtaa ylimääräsiä alt atribuutteja.

2024-09-13 06:46 UTC, lupari requested changes

2024-09-24 13:13 UTC, lupari requested changes

2024-09-24 13:13 UTC, lupari commented on ui/src/app/examination/question/examination-question.component.ts
> +            this.translate?.instant(expanded) +
Miksi kysymysmerkit?

2024-09-24 13:13 UTC, lupari commented on ui/src/app/examination/question/examination-question.component.ts
> +            this.translate?.instant(expanded) +
Voisko käyttää templaatti-stringiä mielummin? Eli ``-syntaksia?

2024-10-14 13:53 UTC, lupari approved these changes

2024-10-15 05:26 UTC, merged