CSCEXAM-1367 Fix unclear exam participant listing and control
CSCfi/exam pull request #1165
Opened 2024-10-10 12:37 UTC by VirmasaloA

2024-10-11 12:42 UTC, lupari requested changes

2024-10-11 12:42 UTC, lupari commented on ui/src/styles.scss
> +.hover-grey:hover {
Voisko tälle olla parempi paikka vaikka ui/src/app/exam/exam.shared.scss? Kaiketi tuota käytetään vain siellä examin editoinnissa?

2024-10-14 10:57 UTC, VirmasaloA commented on ui/src/styles.scss
> +.hover-grey:hover {
Joo, mut mie suunnittelin sen niin että sitä voi käyttää kaikissa paikoissa tarvittaessa. Varmasti tulee lisää listoja missä tommonen hover indikaattori on käyttöä helpottava. Nyt se on vaan ekan kerran käytössä. Mut voidaan siirtää se tonne shared.scss

2024-10-14 13:55 UTC, lupari commented on ui/src/styles.scss
> +.hover-grey:hover {
Joo no ihan miten vaan. Lähinnä vaan siksi kysyin koska pyrkimyksenä on pitää globaali tyylitiedosto mahdollisimman pienenä. Tuon voi siirtää sinne sitten kun käyttöä on laajemmin :)

2024-10-14 13:56 UTC, lupari approved these changes
Jos viitsit siirtää tuon tyylin eri tiedostoon vielä toistaiseksi.

2024-10-15 12:50 UTC, lupari approved these changes

2024-10-15 12:51 UTC, merged