CSCEXAM-1356 Add shortens to exam list
CSCfi/exam pull request #1172
Opened 2024-10-22 13:03 UTC by VirmasaloA

2024-10-23 15:47 UTC, lupari commented on ui/src/app/shared/sorting/table-sort.component.ts
>      getSortClass = () =>
Miksi tämä on jompaa kumpaa tyyppiä?

2024-10-23 15:50 UTC, lupari commented on ui/src/app/dashboard/staff/teacher/categories/exam-list-category.component.html
> +                            sliced="{{ true }}"
[sliced]="true" kenties?

2024-10-23 15:51 UTC, lupari requested changes
Luulisi, että tuo voisi olla boolean-only?

2024-10-24 11:52 UTC, VirmasaloA commented on ui/src/app/shared/sorting/table-sort.component.ts
>      getSortClass = () =>
Miulla se typescript kieltäyty buildaamasta pelkällä booleanilla. Tää ei oo hyvä ratkasu, mut sillä se buildas.
HTML filussa oli insert sliced="{{true}}" ja typescript ei hyväksyny sitä booleaniks..

2024-10-25 09:38 UTC, lupari approved these changes

2024-10-25 09:45 UTC, merged