CSCEXAM-1149 Autofocus and tabindex fixes
CSCfi/exam pull request #950
Opened 2023-04-13 07:25 UTC by lupari

2023-04-13 11:34 UTC, VirmasaloA requested changes

2023-04-13 12:09 UTC, lupari commented on ui/src/app/administrative/users/users.component.html
> -                                            tabindex="0"
Jees, vähän hätäisesti noita poistin. Suurin osa niistä tosin oli buttoneissa ja linkeissä etc.

2023-04-13 12:13 UTC, lupari commented on ui/src/app/administrative/users/users.component.html
> -                                            tabindex="0"
Ehkä niiden ois kenties parempi olla buttoneita jos niihin tarvii kohdistaa?

2023-04-13 12:13 UTC, lupari commented on ui/src/app/examination/navigation/examination-toolbar.component.html
> -                tabindex="1"
tabindex positiivisella arvolla tosin ei ole suositeltavaa kuin jossain todella poikkeuksellisissa tapauksessa.
https://www.a11yproject.com/posts/how-to-use-the-tabindex-attribute/

2023-04-13 13:20 UTC, lupari commented on ui/src/app/administrative/users/users.component.html
> -                                            tabindex="0"
Ainakin noissa dropdowneissa näköjään tabit toimii automaagisesti oli indeksöity tai ei. Itse en ainakaan huomaa mitään toiminnallista eroa.

2023-04-13 14:11 UTC, lupari commented on ui/src/app/administrative/users/users.component.html
> -                                            tabindex="0"
Vaihdoin nyt noita legacy dropdowneja käyttämään buttoneita, kuten on ainakin bootstrapin dokkarin mukaan hyvä käyttää.

2023-04-14 07:53 UTC, VirmasaloA approved these changes

2023-04-14 11:54 UTC, merged