CSCEXAM-1182 Fix ClozeTestAnswer aria-label
CSCfi/exam pull request #970
Opened 2023-05-22 07:43 UTC by VirmasaloA

2023-05-25 09:57 UTC, lupari commented on ui/.bsp/sbt.json
> +{"name":"sbt","version":"1.5.5","bspVersion":"2.0.0-M5","languages":["scala"],"argv":["/Library/Java/JavaVirtualMachines/temurin-11.jdk/Contents/Home/bin/java","-Xms100m","-Xmx100m","-classpath","/us
Tän ei varmaan pitäisi olla versionhallinnassa.

2023-05-25 09:58 UTC, lupari requested changes
Mitäs nää muut muutokset ovat?

2023-05-29 11:58 UTC, VirmasaloA commented on ui/project/build.properties
> +sbt.version=1.5.5
Juu näiden ei pitäs olla mukana.

2023-05-29 19:57 UTC, lupari approved these changes

2023-05-31 06:46 UTC, merged