CSCEXAM-971 Add button to hide over a year old exception times from availability …
CSCfi/exam pull request #998
Opened 2023-09-07 12:40 UTC by VirmasaloA

…view

2023-09-07 14:33 UTC, lupari commented on ui/src/app/facility/rooms/availability.component.html
> +                    oldExceptionsHidden ? translate.instant('sitnet_on') : translate.instant('sitnet_off')
Parempi käyttää näissä translate-pipea ja vaikka ngIf:iä.

2023-09-07 14:34 UTC, lupari requested changes
Translate-servicen ei tulisi olla public-jäsen komponentissa.

2023-09-11 13:02 UTC, VirmasaloA commented on ui/src/app/facility/rooms/availability.component.html
> +                    oldExceptionsHidden ? translate.instant('sitnet_on') : translate.instant('sitnet_off')
```
 <button (click)="oldExceptionsHidden = !oldExceptionsHidden" class="btn btn-secondary marb20">
                {{ 'sitnet_hide_over_year_old' | translate }} ({{
                    oldExceptionsHidden ? ('sitnet_on' | translate) : ('sitnet_off' | translate)
                }})
            </button>
```

vai 

 ```
   <button *ngIf="oldExceptionsHidden" (click)="oldExceptionsHidden = !oldExceptionsHidden" class="btn btn-secondary marb20">
                {{ 'sitnet_hide_over_year_old' | translate }} ({{'sitnet_off' | translate }})
            </button>
          <button *ngIf="!oldExceptionsHidden" (click)="oldExceptionsHidden = !oldExceptionsHidden" class="btn btn-secondary marb20">
            {{ 'sitnet_hide_over_year_old' | translate }} ({{'sitnet_on' | translate }})
          </button>
```

2023-09-11 13:12 UTC, lupari commented on ui/src/app/facility/rooms/availability.component.ts
> +        public translate: TranslateService,
Tämän voinee poistaa

2023-09-11 13:13 UTC, lupari commented on ui/src/app/facility/rooms/availability.component.html
> +                    oldExceptionsHidden ? translate.instant('sitnet_on') : translate.instant('sitnet_off')
Ehkä tuo ylempi jos kerran toimii :)

2023-09-12 07:34 UTC, merged